import React, {useEffect, useRef, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient, type Session} from '@supabase/supabase-js';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import './style.css';

type Product={id:string;aoi_name:string;recipe:string;status:'draft'|'approved'|'published';accuracy?:{metric:string;value:number};drift?:{flagged:boolean};geometry:{type:string;coordinates:unknown};model_name:string;model_version:string;scene_ids:string[];processed_at:string;cloud_threshold:number};
type Aoi={id:string;name:string;cadence_days:number;cloud_threshold:number;product_recipes:string[];enabled:boolean;last_scheduled_at?:string};
type Tenant={id:string;name:string;slug:string;role:'viewer'|'reviewer'|'admin'};

const API=import.meta.env.VITE_API_URL||(location.hostname==='localhost'?'http://localhost:8081':'');
const SUPABASE_URL=import.meta.env.VITE_SUPABASE_URL||'https://ddtxieatemxpnapqvcaf.supabase.co';
const SUPABASE_PUBLISHABLE_KEY=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY||'sb_publishable_RzIkiSG3a9SR3lXBJ_B__w_UJRXZreg';
const supabase=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});

function App(){
 const [session,setSession]=useState<Session|null>(null); const [authLoading,setAuthLoading]=useState(true); const [authError,setAuthError]=useState('');
 const [tenants,setTenants]=useState<Tenant[]>([]); const [tenant,setTenant]=useState(''); const [accessLoading,setAccessLoading]=useState(false);
 const [products,setProducts]=useState<Product[]>([]); const [selected,setSelected]=useState<Product>(); const mapNode=useRef<HTMLDivElement>(null); const map=useRef<maplibregl.Map|null>(null);
 const [aois,setAois]=useState<Aoi[]>([]); const [runAoi,setRunAoi]=useState(''); const [running,setRunning]=useState(false); const [runMessage,setRunMessage]=useState('');

 useEffect(()=>{let active=true;supabase.auth.getSession().then(({data,error})=>{if(!active)return;if(error)setAuthError(error.message);setSession(data.session);setAuthLoading(false)});const {data}=supabase.auth.onAuthStateChange((_event,next)=>{setSession(next);setAuthLoading(false)});return()=>{active=false;data.subscription.unsubscribe()}},[]);
 async function discoverTenants(nextSession:Session){setAccessLoading(true);setAuthError('');try{const response=await fetch(`${API}/api/me/tenants`,{headers:{authorization:`Bearer ${nextSession.access_token}`}});if(!response.ok)throw new Error(await response.text());const memberships:Tenant[]=await response.json();setTenants(memberships);const remembered=sessionStorage.getItem('pacificeo_tenant');const selectedTenant=memberships.find(item=>item.id===remembered)?.id||memberships[0]?.id||'';setTenant(selectedTenant);if(selectedTenant)sessionStorage.setItem('pacificeo_tenant',selectedTenant)}catch(error){setAuthError(error instanceof Error?error.message:'Unable to check workspace access.')}finally{setAccessLoading(false)}}
 useEffect(()=>{if(session)discoverTenants(session);else{setTenants([]);setTenant('');setProducts([]);setAois([])}},[session]);

 async function request(path:string,init?:RequestInit){if(!session||!tenant)throw new Error('Workspace access is not ready.');const response=await fetch(API+path,{...init,headers:{'content-type':'application/json',authorization:`Bearer ${session.access_token}`,'x-tenant-id':tenant,...init?.headers}});if(response.status===401){await supabase.auth.refreshSession();throw new Error('Your session was refreshed. Please try again.')}if(!response.ok)throw new Error(await response.text());return response.json()}
 async function refresh(){if(session&&tenant){const [nextProducts,nextAois]=await Promise.all([request('/api/products'),request('/api/aois')]);setProducts(nextProducts);setAois(nextAois);setRunAoi(current=>nextAois.some((a:Aoi)=>a.id===current&&a.enabled)?current:nextAois.find((a:Aoi)=>a.enabled)?.id||'')}}
 useEffect(()=>{refresh().catch(error=>setRunMessage(error instanceof Error?error.message:'Unable to load workspace.'))},[session,tenant]);
 useEffect(()=>{if(!session||!tenant||!mapNode.current||map.current)return;map.current=new maplibregl.Map({container:mapNode.current,style:'https://demotiles.maplibre.org/style.json',center:[178,-17],zoom:4});return()=>{map.current?.remove();map.current=null}},[session,tenant]);
 useEffect(()=>{const currentMap=map.current;if(!currentMap)return;const data={type:'FeatureCollection' as const,features:products.map(product=>({type:'Feature' as const,geometry:product.geometry,properties:{id:product.id,status:product.status}}))};const update=()=>{if(currentMap.getSource('products'))(currentMap.getSource('products') as maplibregl.GeoJSONSource).setData(data as never);else{currentMap.addSource('products',{type:'geojson',data:data as never});currentMap.addLayer({id:'products-fill',type:'fill',source:'products',paint:{'fill-color':['match',['get','status'],'draft','#f59e0b','approved','#38bdf8','#16a34a'],'fill-opacity':.42}})}};currentMap.loaded()?update():currentMap.once('load',update)},[products]);

 async function signIn(){setAuthError('');const {error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:location.origin}});if(error)setAuthError(error.message)}
 async function signOut(){await supabase.auth.signOut();sessionStorage.removeItem('pacificeo_tenant');setRunMessage('')}
 async function action(id:string,verb:'approve'|'publish'){await request(`/api/products/${id}/${verb}`,{method:'POST',body:verb==='approve'?JSON.stringify({comment:'Approved in PacificEO dashboard'}):undefined});await refresh()}
 async function runNow(){if(!runAoi)return;setRunning(true);setRunMessage('Checking the latest Sentinel-2 acquisitions…');try{const result=await request(`/api/aois/${runAoi}/run`,{method:'POST'});const aoi=aois.find(item=>item.id===runAoi);setRunMessage(result.scene_count?`${result.scene_count} qualifying scene${result.scene_count===1?'':'s'} registered. Processing run queued.`:`No qualifying scenes found in the last ${aoi?.cadence_days??'configured'} days.`);await refresh()}catch(error){setRunMessage(error instanceof Error?`Workflow failed: ${error.message}`:'Workflow failed.')}finally{setRunning(false)}}

 if(authLoading)return <main className="login"><span className="eyebrow">Viti Waitui</span><h1>PacificEO Monitor</h1><p>Opening your secure workspace…</p></main>;
 if(!session)return <main className="login"><span className="eyebrow">Viti Waitui</span><h1>PacificEO Monitor</h1><p>Sign in with your approved Google account to access Earth Observation products.</p><button className="google" onClick={signIn}><span aria-hidden="true">G</span> Continue with Google</button>{authError&&<p className="error" role="alert">{authError}</p>}<small>Access is limited to assigned PacificEO organisations.</small></main>;
 if(accessLoading)return <main className="login"><span className="eyebrow">Viti Waitui</span><h1>PacificEO Monitor</h1><p>Checking your organisation access…</p></main>;
 if(!tenant)return <main className="login"><span className="eyebrow">Viti Waitui</span><h1>Access not assigned</h1><p>Your Google account is signed in, but it has not been assigned to a PacificEO organisation.</p>{authError&&<p className="error" role="alert">{authError}</p>}<button onClick={signOut}>Sign out</button></main>;

 const queue=products.filter(product=>product.status!=='published');const currentTenant=tenants.find(item=>item.id===tenant);
 return <main><header><div><span className="eyebrow">{currentTenant?.name||'PacificEO'}</span><h1>PacificEO Monitor</h1></div><div className="header-actions">{tenants.length>1&&<label className="tenant-picker">Organisation<select value={tenant} onChange={event=>{setTenant(event.target.value);sessionStorage.setItem('pacificeo_tenant',event.target.value)}}>{tenants.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label>}<div className="workflow"><label htmlFor="workflow-aoi">AOI</label><select id="workflow-aoi" value={runAoi} onChange={event=>setRunAoi(event.target.value)} disabled={running}>{aois.filter(aoi=>aoi.enabled).map(aoi=><option key={aoi.id} value={aoi.id}>{aoi.name} · cloud ≤ {aoi.cloud_threshold}%</option>)}</select><button onClick={runNow} disabled={running||!runAoi}>{running?'Running…':'Run now'}</button></div>{runMessage&&<small className="run-message" role="status">{runMessage}</small>}<button className="quiet" onClick={signOut}>Sign out</button></div></header><section className="layout"><div className="map" ref={mapNode}/><aside><h2>Review queue <b>{queue.length}</b></h2>{queue.length===0&&<p className="empty">No products await review. Run an AOI workflow to check for qualifying scenes.</p>}{queue.map(product=><article key={product.id} onClick={()=>setSelected(product)}><span className={`status ${product.status}`}>{product.status}</span><h3>{product.aoi_name}</h3><p>{product.recipe}</p><small>{product.accuracy?`${product.accuracy.metric}: ${(product.accuracy.value*100).toFixed(1)}%`:'Accuracy not assessed'}</small><div>{product.status==='draft'&&<button onClick={event=>{event.stopPropagation();action(product.id,'approve')}}>Approve</button>}{product.status==='approved'&&<button onClick={event=>{event.stopPropagation();action(product.id,'publish')}}>Publish</button>}</div></article>)}</aside>{selected&&<section className="provenance"><button className="close" onClick={()=>setSelected(undefined)}>×</button><span className="eyebrow">Provenance</span><h2>{selected.recipe}</h2><dl><dt>Model</dt><dd>{selected.model_name}<br/>{selected.model_version}</dd><dt>Scenes</dt><dd>{selected.scene_ids.join(', ')}</dd><dt>Cloud gate</dt><dd>{selected.cloud_threshold}%</dd><dt>Processed</dt><dd>{new Date(selected.processed_at).toLocaleString()}</dd><dt>Validation</dt><dd>{selected.accuracy?`${selected.accuracy.metric}: ${selected.accuracy.value}`:'Not assessed'}</dd><dt>Drift</dt><dd>{selected.drift?.flagged?'Flagged for review':'No flag'}</dd></dl></section>}</section></main>;
}

createRoot(document.getElementById('root')!).render(<App/>);
